# -*- coding: utf-8 -*-
"""How to find average of N numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydfo2ZJ-Lv1aYS6uUfFPHszJ6h9DsF0o
"""

num=int(input("How many number ?"))
total_sum=0
for n in range(num):
  number=float(input('Enter you number:'))
  total_sum += number
avg=total_sum/num
print('The average number is :',avg)

