# -*- coding: utf-8 -*-
"""oop_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJTBJG9bNzEb79FoztpAKfF-gPZ5fF8t
"""

class rofiq:
  name=''
  number=''
  id=''
a=rofiq()
a.name='amimul'
print(a.name)

b=rofiq()
b.id=1929035
print(b.id)

# Inheritance
# Catalist....
# combinde two class
class baba:
  #parent class,base class
  car='BMW'
  tk='1000 cr'
  home='10'
class kaka(baba):
  #child class,another class,derived class
  brokenphon=''
  brokenhome=''
k=kaka()
print(k.car)

#multi_inheritance
class baba:
  #parent class,base class
  car='BMW'
  tk='1000 cr'
  home='10'
class baba1:
  camera='ultra'
class baba2:
  iphon='iphon 16'
  laptop='asus'
  camer='fifine'
class kaka(baba,baba1,baba2):
  #child class,another class,derived class
  brokenphon=''
  brokenhome=''
k=kaka()
print(k.car)
print(k.laptop)

# multi_level inheretance
class baba:
  #parent class,base class
  car='BMW'
  tk='1000 cr'
  home='10'
class son1(baba):
  camera='ultra'
class son2(son1):
  iphon='iphon 16'
  laptop='asus'
  camer='fifine'
class son3(son2):
  #child class,another class,derived class
  brokenphon=''
  brokenhome=''
s=son3()
print(s.car)
# print(s.laptop)

