# -*- coding: utf-8 -*-
"""Write a Python program to calculate the average of all elements in a given list of integers..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkcM9tEGim7Kk1syAM_qMwear0MbC39M
"""

# Write a Python program to calculate the average of all elements in a given list of integers.
a=[2,3,4,5,6,7]
num=0
for i in a:
  num=(num+i)
avg=num/len(a)
print(avg)

