# -*- coding: utf-8 -*-
"""Write a Python program to find the sum of all elements in a given list of integers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSitEDUYvnTdnwa_EviJD4oHGKwyVFZz
"""

# Write a Python program to find the sum of all elements in a given list of integers
a=[1,2,3,4,5,6]
sum=0
for i in a:
  sum=sum+i
print(sum)

