# -*- coding: utf-8 -*-
"""Write a Python program to find the maximum and minimum values in a given list of integers..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYyNXM3GRIFmCipOTXNg5GMDkt3aOc4a
"""

#  Write a Python program to find the maximum and minimum values in a given list of integers.
a=[7,4,5,8,3]
max(a)

